var files =
[
    [ "attributes.c", "attributes_8c.html", "attributes_8c" ],
    [ "attributes.h", "attributes_8h.html", "attributes_8h" ],
    [ "constantpool.c", "constantpool_8c.html", "constantpool_8c" ],
    [ "constantpool.h", "constantpool_8h.html", "constantpool_8h" ],
    [ "debugging.c", "debugging_8c.html", null ],
    [ "debugging.h", "debugging_8h.html", null ],
    [ "fields.c", "fields_8c.html", "fields_8c" ],
    [ "fields.h", "fields_8h.html", "fields_8h" ],
    [ "framestack.c", "framestack_8c.html", "framestack_8c" ],
    [ "framestack.h", "framestack_8h.html", "framestack_8h" ],
    [ "instructions.c", "instructions_8c.html", "instructions_8c" ],
    [ "instructions.h", "instructions_8h.html", "instructions_8h" ],
    [ "javaclass.c", "javaclass_8c.html", "javaclass_8c" ],
    [ "javaclass.h", "javaclass_8h.html", "javaclass_8h" ],
    [ "jvm.c", "jvm_8c.html", "jvm_8c" ],
    [ "jvm.h", "jvm_8h.html", "jvm_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "methods.c", "methods_8c.html", "methods_8c" ],
    [ "methods.h", "methods_8h.html", "methods_8h" ],
    [ "natives.c", "natives_8c.html", "natives_8c" ],
    [ "natives.h", "natives_8h.html", "natives_8h" ],
    [ "opcodes.c", "opcodes_8c.html", "opcodes_8c" ],
    [ "opcodes.h", "opcodes_8h.html", "opcodes_8h" ],
    [ "operandstack.c", "operandstack_8c.html", "operandstack_8c" ],
    [ "operandstack.h", "operandstack_8h.html", "operandstack_8h" ],
    [ "readfunctions.c", "readfunctions_8c.html", "readfunctions_8c" ],
    [ "readfunctions.h", "readfunctions_8h.html", "readfunctions_8h" ],
    [ "utf8.c", "utf8_8c.html", "utf8_8c" ],
    [ "utf8.h", "utf8_8h.html", "utf8_8h" ],
    [ "validity.c", "validity_8c.html", "validity_8c" ],
    [ "validity.h", "validity_8h.html", "validity_8h" ]
];